name: Build APK (FINAL FIX - Gradle Version Lock)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Kita tetap pakai JDK 17, ini tidak masalah
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # --- INI BAGIAN PALING PENTING ---
    # Kita paksa workflow untuk menggunakan Gradle v7.5.1
    # yang 100% cocok dengan Android Gradle Plugin di proyek Anda.
    - name: Setup and Lock Gradle Version
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '7.5.1'

    # Sekarang kita build. Tidak perlu regenerate wrapper lagi
    # karena kita sudah pakai versi Gradle yang benar.
    - name: Build APK with Gradle
      run: |
        cd content/FloatingKeyboard
        chmod +x ./gradlew
        bash ./gradlew assembleDebug

    # Upload APK
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bajingan-apk
        path: content/FloatingKeyboard/app/build/outputs/apk/debug/app-debug.apk
